services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=webserver'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27018:27017'
    networks:
        - ll_network
    volumes:
        - mongodb_data:/data/db

  server:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
    environment:
      - 'MONGO_URI=mongodb://root:secret@mongodb:27018/webserver'
    networks:
        - ll_network

volumes:
    mongodb_data:

networks:
    ll_network:
        driver: bridge
